changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: Security and privacy
      labels:
        - security
        - privacy
    - title: Accessibility
      labels:
        - accessibility
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies and maintenance
      labels:
        - dependencies
        - maintenance
        - chore
    - title: Other changes
      labels:
        - '*'
